CREATE TABLE IF NOT EXISTS public.users
(
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    balance DECIMAL(10, 2) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
    updatedAt TIMESTAMP NOT NULL DEFAULT NOW()
    
)